version: "3.8"

services:
  node:
    image: node
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - "8081"
    command: "npm start"

  volumes:
      - ./:/home/node/app